apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: basket-api-monitor
  namespace: eshop-dev
  labels:
    release: monitoring # This MUST match the name of your Helm release
spec:
  selector:
    matchLabels:
      app: basket-api # Matches the label in your Basket deployment
  endpoints:
  - port: http
    path: /metrics