apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eshop-services
  namespace: monitoring          # must match where Prometheus is installed
  labels:
    release: monitoring          # must match the Helm release name
spec:
  namespaceSelector:
    matchNames:
      - NAMESPACE_PLACEHOLDER
  selector:
    matchLabels:
      monitor: "true"            
  endpoints:
    - port: http
      targetPort: 80
      path: /metrics
      interval: 15s
      scheme: http