grafana:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    hosts:
      - grafana.dev.jan26-group6-eshoponcontainers.abrdns.com

prometheus:
  prometheusSpec:
    scrapeInterval: 30s      # scrape every 60s instead of 15s (4x less work)
    evaluationInterval: 30s
    retention: 1d          # short retention, dev doesn't need history
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi   # small disk, it's just dev

# Disable heavy components not needed for the course
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
<<<<<<< HEAD
=======
  enabled: false
alertmanager:
>>>>>>> origin/main
  enabled: false