{{- $ingressPath := include "pathBase" . -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ template "apigwws.fullname" . }}-strip
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  stripPrefix:
    prefixes:
      - {{ $ingressPath }}
